// SPDX-License-Identifier: GPL-3.0-or-later WITH Cyberfidget-HAL-exception
// Copyright (c) 2023-2026 Dismo Industries LLC

#ifndef GLOBALS_H
#define GLOBALS_H

#include <Arduino.h>
#include <time.h>
#include "esp_log.h"
#include "HAL.h"

// Global timers
extern unsigned long millis_NOW;
extern unsigned long millisOldHeartbeat;
extern unsigned long millis_HAL_TASK_200MS;
extern unsigned long millis_APP_TASK_200MS;
extern unsigned long millis_HAL_TASK_50MS;
extern unsigned long millis_HAL_TASK_20MS;
extern unsigned long millis_APP_TASK_20MS;
extern unsigned long millis_APP_LASTINTERACTION;
extern int TASK_20MS;
extern int TASK_50MS;
extern int TASK_200MS;
extern int TASK_LASTINTERACT;

extern const char *TAG_MAIN;

// App modes
extern int  appActive;
extern int  appActiveSaved;
extern int  appPreviously;

// Some booleans for states
extern bool reactionGameEnabled;
extern volatile bool buttonPressed;

// Button counters
constexpr int numButtons = 6;
extern int buttonCounter[numButtons];
extern int buttonCounterSaved[numButtons];

// WiFi
extern char wifiAP_SSID[];
extern bool isTryingToConnect;

// Clock
extern bool clockScreenEnabled;
extern struct tm currentTime;

// Audio beep logic
extern bool beepActive;
extern float beepFrequency;

// Firmware version surface. Values come from generated/version.h, which is
// (re)generated by scripts/generate_version.py before every build. These are
// in Globals (not HAL) because they're build-time identification — pure
// constants, not hardware abstractions. Apps and the WASM emulator both
// consume them without going through any peripheral shim.
const char* getFirmwareVersionString();   // e.g. "1.1.0+508ea44" or "...-dirty"
uint32_t    getFirmwareVersion();         // VERSION_ENCODE(major, minor, patch)
const char* getFirmwareGitHash();         // short hash or "unknown"
const char* getFirmwareBuildType();       // "release"/"prerelease"/"dev"/"dirty"/...
const char* getFirmwareBuildTimestamp();  // ISO-8601 UTC

#endif // GLOBALS_H
