#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2023-2026 Dismo Industries LLC
# Build CyberFidget WASM for the browser emulator.
#
# Prerequisites: Emscripten SDK installed at one of:
#   - <cyberfidget-workspace>/emsdk      (preferred — co-located with the repos)
#   - $HOME/emsdk
#   - or set EMSDK_ROOT to override
#
# Install steps (one-time):
#   git clone https://github.com/emscripten-core/emsdk.git
#   cd emsdk && ./emsdk install 3.1.51 && ./emsdk activate 3.1.51
#
# You do NOT need to source emsdk_env.sh yourself — this script auto-
# activates from whichever location it finds.
#
# Usage:
#   ./build_wasm.sh
#     → Build default demo (output: build/cyberfidget.js, build/cyberfidget.wasm)
#
#   ./build_wasm.sh MyApp.h MyApp.cpp
#     → Build custom app (copies files to wasm/app/, builds with WASM_APP=Custom)
#     → Output: build/cyberfidget.js, build/cyberfidget.wasm (use in website or drag .wasm)
#
# After building, copy build/cyberfidget.js and build/cyberfidget.wasm to the
# website's wasm/ directory, or use the website's "Load from File" if available.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"
APP_DIR="$SCRIPT_DIR/app"
BUILD_DIR="$SCRIPT_DIR/build"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Regenerate version.h before any compilation. Standalone mode of the same
# script PlatformIO uses, branded with FW_BUILD_TYPE="wasm".
echo "=== Generating wasm/generated/version.h ==="
# Prefer python3 (Linux/macOS); fall back to python (Windows installers often
# only register the unversioned name). Adjust if neither is on PATH.
PYTHON=$(command -v python3 || command -v python)
if [ -z "$PYTHON" ]; then
    echo "Error: neither python3 nor python found on PATH." >&2
    exit 1
fi
CYBERFIDGET_BUILD_TYPE_OVERRIDE=wasm \
    "$PYTHON" "$REPO_ROOT/scripts/generate_version.py" \
        --standalone \
        --out "$SCRIPT_DIR/generated/version.h" \
        --repo-root "$REPO_ROOT"

# Locate Emscripten. If emcc isn't already on PATH, look in a few known
# places and source emsdk_env.sh automatically. Override with EMSDK_ROOT.
if ! command -v emcc &>/dev/null; then
    EMSDK_TRY=""
    if [ -n "${EMSDK_ROOT:-}" ] && [ -f "$EMSDK_ROOT/emsdk_env.sh" ]; then
        EMSDK_TRY="$EMSDK_ROOT"
    fi
    # Workspace-co-located install: <cyberfidget-workspace>/emsdk
    if [ -z "$EMSDK_TRY" ] && [ -f "$SCRIPT_DIR/../../emsdk/emsdk_env.sh" ]; then
        EMSDK_TRY="$SCRIPT_DIR/../../emsdk"
    fi
    # User-profile install
    if [ -z "$EMSDK_TRY" ] && [ -f "$HOME/emsdk/emsdk_env.sh" ]; then
        EMSDK_TRY="$HOME/emsdk"
    fi

    if [ -z "$EMSDK_TRY" ]; then
        echo "Emscripten not found. Either:"
        echo "  - install at one of: $SCRIPT_DIR/../../emsdk, \$HOME/emsdk"
        echo "  - or set EMSDK_ROOT to your install path"
        echo "  - or activate emsdk manually before running this script"
        echo "Reference: https://emscripten.org/docs/getting_started/downloads.html"
        exit 1
    fi

    echo "=== Activating Emscripten at $EMSDK_TRY ==="
    # shellcheck source=/dev/null
    source "$EMSDK_TRY/emsdk_env.sh"
    if ! command -v emcc &>/dev/null; then
        echo "ERROR: emsdk_env.sh ran but emcc still not on PATH. Check $EMSDK_TRY."
        exit 1
    fi
fi

if [ $# -eq 0 ]; then
    echo "=== Building default WASM demo ==="
    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"
    emcmake cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
    emmake ninja
    echo ""
    echo "Done. Output: build/cyberfidget.js, build/cyberfidget.wasm"
    exit 0
fi

if [ $# -ne 2 ]; then
    echo "Usage: $0 [AppName.h AppName.cpp]"
    echo "  No args: build default demo"
    echo "  Two args: build custom app (files copied to wasm/app/)"
    exit 1
fi

H_FILE="$1"
CPP_FILE="$2"
if [ ! -f "$H_FILE" ]; then
    echo "Error: $H_FILE not found"
    exit 1
fi
if [ ! -f "$CPP_FILE" ]; then
    echo "Error: $CPP_FILE not found"
    exit 1
fi

# Base name from header (e.g. MyApp.h → MyApp)
BASE_H="${H_FILE##*/}"
APP_NAME="${BASE_H%.h}"

mkdir -p "$APP_DIR"
cp "$H_FILE" "$APP_DIR/$APP_NAME.h"
cp "$CPP_FILE" "$APP_DIR/$APP_NAME.cpp"

# app_include.h so main_wasm.cpp can include the custom app
echo "// Generated by build_wasm.sh - do not edit" > "$APP_DIR/app_include.h"
echo "#include \"App.h\"" >> "$APP_DIR/app_include.h"
echo "#include \"$APP_NAME.h\"" >> "$APP_DIR/app_include.h"

echo "=== Building custom WASM app: $APP_NAME ==="
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"
emcmake cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DWASM_APP=Custom -DCUSTOM_APP_NAME="$APP_NAME"
emmake ninja

echo ""
echo "Done. Output: build/cyberfidget.js, build/cyberfidget.wasm"
echo "Copy to the website's wasm/ directory or load the .wasm file in the emulator."
exit 0
