// SPDX-License-Identifier: GPL-3.0-or-later WITH Cyberfidget-HAL-exception
// Copyright (c) 2023-2026 Dismo Industries LLC

#include "MenuManager.h"
#include "Flashlight.h"
#include "Booper.h"
#include "PowerManager.h"
#include "MatrixScreensaver.h"
#include "BreakoutGame.h"
#include "DinoGame.h"
#include "ClockDisplay.h"
#include "SimonSaysGame.h"
#include "SPHFluidGame.h"
#include "ExampleScreens.h"
#include "ReactionTimeGame.h"
#include "SerialDisplayApp.h"
#include "BootAnimation.h"
#include "StratagemGame.h"
#include "GraveyardScreensaver.h"
#include "Ghosts.h"
#include "Eye.h"
#include "MyScreensaver.h"
#include "Splooty.h"
#include "Spaceship.h"
#include "MusicPlayerApp.h"
#include "WebPortalApp.h"
#include "BewilderYourBrain.h"
#include "PixelWaterfallGame.h"
